# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  sequence_diagram: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true

integrations:
  gitleaks:
    enabled: true
    fail_on_secrets: true

  checkov:
    enabled: true
    soft_fail: false

  actionlint:
    enabled: true
    strict_mode: true

testing:
  enabled: true
  test_framework: "pytest"
  test_paths:
    - "tests/"
  fail_on_test_failure: true

linting:
  enabled: true
  linter: "flake8"
  lint_paths:
    - "src/"
  strict_mode: true
